import { LanguageOption, TemplateCategory, TemplateType, TemplateFormData } from './types';

export const INITIAL_FORM_DATA: TemplateFormData = {
  name: '',
  category: 'MARKETING',
  templateType: 'STANDARD',
  language: 'pt_BR',
  headerFormat: 'NONE',
  headerText: '',
  bodyText: '',
  footerText: '',
  buttons: [],
  bodyExamples: [],
  headerExamples: [],
  addSecurityRecommendation: true,
  carouselCards: [],
  limitedTimeOfferText: '',
  mpmSections: [],
  orderItems: [],
};

export const TEMPLATE_TYPES: Record<
  TemplateCategory,
  Array<{ value: TemplateType; label: string; description: string }>
> = {
  MARKETING: [
    { value: 'STANDARD', label: 'Padrao', description: 'Template padrao com texto, midia e botoes.' },
    { value: 'CATALOG', label: 'Catalogo', description: 'Template para experiencias com catalogo.' },
    { value: 'FLOWS', label: 'Flows', description: 'Template com botao FLOW para abrir um fluxo.' },
    { value: 'CAROUSEL', label: 'Carousel', description: 'Template com cards de midia horizontais.' },
    {
      value: 'LIMITED_TIME_OFFER',
      label: 'Limited-time offer',
      description: 'Template com oferta por tempo limitado e expiracao.',
    },
    { value: 'MPM', label: 'Multi-produto', description: 'Template com secoes de produtos (MPM).' },
  ],
  UTILITY: [
    { value: 'STANDARD', label: 'Padrao', description: 'Template padrao para utilidade.' },
    { value: 'ORDER_DETAILS', label: 'Detalhes do pedido', description: 'Template de detalhes de pedido.' },
    { value: 'FLOWS', label: 'Flows', description: 'Template de utilidade com Flow.' },
  ],
  AUTHENTICATION: [
    { value: 'STANDARD', label: 'Autenticacao', description: 'Template OTP de autenticacao da Meta.' },
    { value: 'CALL_PERMISSION', label: 'Call permission', description: 'Solicitacao de permissao para ligacao.' },
  ],
};

export const LANGUAGES: LanguageOption[] = [
  { value: 'pt_BR', label: 'Portugues (Brasil)' },
  { value: 'pt_PT', label: 'Portugues (Portugal)' },
  { value: 'en', label: 'English' },
  { value: 'en_US', label: 'English (US)' },
  { value: 'en_GB', label: 'English (UK)' },
  { value: 'es', label: 'Espanol' },
  { value: 'es_AR', label: 'Espanol (Argentina)' },
  { value: 'es_MX', label: 'Espanol (Mexico)' },
  { value: 'es_CL', label: 'Espanol (Chile)' },
  { value: 'es_CO', label: 'Espanol (Colombia)' },
  { value: 'fr', label: 'Francais' },
  { value: 'fr_CA', label: 'Francais (Canada)' },
  { value: 'de', label: 'Deutsch' },
  { value: 'it', label: 'Italiano' },
  { value: 'nl', label: 'Nederlands' },
  { value: 'ar', label: 'Arabic' },
  { value: 'ar_EG', label: 'Arabic (Egypt)' },
  { value: 'hi', label: 'Hindi' },
  { value: 'id', label: 'Indonesian' },
  { value: 'ja', label: 'Japanese' },
  { value: 'ko', label: 'Korean' },
  { value: 'zh_CN', label: 'Chinese (Mainland)' },
  { value: 'zh_HK', label: 'Chinese (Hong Kong)' },
  { value: 'zh_TW', label: 'Chinese (Taiwan)' },
  { value: 'tr', label: 'Turkish' },
  { value: 'vi', label: 'Vietnamese' },
  { value: 'ru', label: 'Russian' },
  { value: 'uk', label: 'Ukrainian' },
  { value: 'th', label: 'Thai' },
  { value: 'sv', label: 'Swedish' },
  { value: 'pl', label: 'Polish' },
  { value: 'cs', label: 'Czech' },
  { value: 'da', label: 'Danish' },
  { value: 'fi', label: 'Finnish' },
  { value: 'nb', label: 'Norwegian' },
  { value: 'el', label: 'Greek' },
  { value: 'he', label: 'Hebrew' },
  { value: 'fa', label: 'Persian' },
  { value: 'ur', label: 'Urdu' },
  { value: 'bn', label: 'Bengali' },
  { value: 'ta', label: 'Tamil' },
  { value: 'te', label: 'Telugu' },
  { value: 'mr', label: 'Marathi' },
  { value: 'ml', label: 'Malayalam' },
  { value: 'gu', label: 'Gujarati' },
  { value: 'kn', label: 'Kannada' },
  { value: 'pa', label: 'Punjabi' },
  { value: 'ro', label: 'Romanian' },
  { value: 'hu', label: 'Hungarian' },
  { value: 'sk', label: 'Slovak' },
  { value: 'sl', label: 'Slovenian' },
  { value: 'hr', label: 'Croatian' },
  { value: 'sr', label: 'Serbian' },
  { value: 'bg', label: 'Bulgarian' },
  { value: 'lt', label: 'Lithuanian' },
  { value: 'lv', label: 'Latvian' },
  { value: 'et', label: 'Estonian' },
  { value: 'sw', label: 'Swahili' },
  { value: 'fil', label: 'Filipino' },
  { value: 'ms', label: 'Malay' },
  { value: 'af', label: 'Afrikaans' },
  { value: 'sq', label: 'Albanian' },
  { value: 'az', label: 'Azerbaijani' },
  { value: 'be_BY', label: 'Belarusian' },
  { value: 'ca', label: 'Catalan' },
  { value: 'ka', label: 'Georgian' },
  { value: 'ga', label: 'Irish' },
  { value: 'kk', label: 'Kazakh' },
  { value: 'ky_KG', label: 'Kyrgyz' },
  { value: 'lo', label: 'Lao' },
  { value: 'mk', label: 'Macedonian' },
  { value: 'prs_AF', label: 'Dari (Afghanistan)' },
  { value: 'ps_AF', label: 'Pashto (Afghanistan)' },
  { value: 'rw_RW', label: 'Kinyarwanda' },
  { value: 'si_LK', label: 'Sinhala (Sri Lanka)' },
  { value: 'uz', label: 'Uzbek' },
  { value: 'zu', label: 'Zulu' },
];
